# Generated by Django 4.0.1 on 2022-01-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tours.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='town',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tours.town'),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tours.country'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(to='tours.Hotel'),
        ),
        migrations.AddField(
            model_name='tour',
            name='towns',
            field=models.ManyToManyField(to='tours.Town'),
        ),
        migrations.AlterField(
            model_name='town',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tours.country'),
        ),
    ]
